import type { Messages } from '#src/i18n/index.ts';
import type { CompactTarget } from '#src/recap/domain/compaction.ts';
import type { Lane } from '#src/recap/domain/lane.ts';
import type { Agents } from '#src/ports/agents.ts';
import type { LaneSettling } from '#src/ports/lane-settling.ts';
import type { Notifier } from '#src/ports/notifier.ts';
import type { Boundaries } from '#src/ports/boundaries.ts';
import type { Ledger } from '#src/ports/ledger.ts';
import type { RecapRecords } from '#src/ports/recap-records.ts';
import type { Entry, Mark } from '#src/ports/transcripts.ts';
import type { LaneWeb } from '#src/ports/tab-views.ts';
import type { AutocompactRecords } from '#src/ports/autocompact-records.ts';
import type { Written } from './compaction-brief.ts';
import type { Coverage, CoverageFact } from './brief-coverage.ts';
import type { Records } from './compaction-trail.ts';
import type { LaneEvents } from './lane-events.ts';
import type { CompactionClaims } from './compaction-claims.ts';
import type { CompactionPlans } from '#src/ports/compaction-plans.ts';

export interface CompactionDeps {
    readonly compactionPlans: CompactionPlans;
    readonly agents: Agents;
    readonly notifier: Notifier;
    readonly records: Pick<RecapRecords, 'readRecap'>;
    readonly ledger: Pick<Ledger, 'historyOf'>;
    readonly boundaries: Pick<Boundaries, 'lastBreakAt'>;
    readonly compactions: Records;
    readonly settling: LaneSettling;
    readonly brief: { enabled(): boolean; job(): string | null; write(document: string, own: string, correction?: string): Promise<Written> };
    coverage(): { check(brief: string, facts: readonly CoverageFact[]): Promise<Coverage> } | null;
    readonly decisions: Pick<AutocompactRecords, 'linkLatest' | 'amend'> | null;
    answer?(id: string, pane: string, stage: string): void;
    readonly typing?: { acquire(pane: string): Promise<'taken' | 'busy' | 'unavailable'>; release(pane: string): Promise<void> };
    readonly events?: LaneEvents;
    readonly claims: CompactionClaims;
    recent(lane: Lane): Promise<readonly Entry[]>;
    marks(lane: Lane): Promise<readonly Mark[]>;
    pause(ms: number): Promise<void>;
    now(): number;
    readonly webs: { of(pane: string): LaneWeb | null };
    lanes(tab: string): readonly Lane[];
    focused(tab: string): Promise<string | null>;
    refresh(tab: string, lanes: readonly Lane[]): Promise<void>;
    target(): CompactTarget;
    messages(): Messages;
    log(line: string): void;
}
